version: '3.9'
services:
  stockstack:
    build:
      context: .
      dockerfile: ./deployment/Dockerfile
    image: stockstack-frontend:1.0.0
    volumes:
      - ./deployment/nginx.conf:/etc/nginx/nginx.conf
      - ./build:/html/stockstack
    ports:
      - 3002:80
      - 3000:3000
      - 3006:3006
    networks:
      - default

networks:
  default:
    name: stockstack
